import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {mkdtemp,readFile,writeFile,realpath} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,dirname,delimiter} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
const manager=join(root,'node_modules/pnpm/bin/pnpm.cjs');
const output=await mkdtemp(join(tmpdir(),'offline-independent-pack-'));
const run=(args,cwd=root)=>execFileSync(process.execPath,[manager,...args],{cwd,stdio:'inherit',timeout:300000,env:{...process.env,PATH:dirname(process.execPath)+delimiter+process.env.PATH}});
run(['pack','--pack-destination',output]);
const archive=join(output,'effortlessmetrics-astro-offline-0.1.4.tgz');
const entries=execFileSync('tar',['-tf',archive],{encoding:'utf8'}).trim().split(/\r?\n/).sort();
const expected=['CHANGELOG.md','LICENSE','LICENSE-MIT','LICENSE-APACHE','README.md','WORKBOX-LICENSE','package.json','src/client.js','src/client.d.ts','src/integration.mjs','src/integration.d.ts','src/worker.mjs'].map(n=>'package/'+n).sort();
assert.deepEqual(entries,expected);
await writeFile(join(output,'package.json'),JSON.stringify({name:'neutral-offline-consumer',private:true,type:'module',dependencies:{'@effortlessmetrics/astro-offline':'file:'+archive.replaceAll('\\','/'),astro:'7.3.5'}},null,2));
run(['install','--ignore-scripts'],output);
const installed=join(output,'node_modules/@effortlessmetrics/astro-offline');
assert.ok((await realpath(installed)).startsWith(await realpath(output)));
const manifest=JSON.parse(await readFile(join(installed,'package.json')));
assert.equal(manifest.version,'0.1.4');
assert.deepEqual(Object.keys(manifest.exports).sort(),['./client','./integration']);
await writeFile(join(output,'consumer-types.ts'),await readFile(join(root,'tests/types.ts')));
execFileSync(process.execPath,[join(root,'node_modules/typescript/bin/tsc'),'--noEmit','--strict','--skipLibCheck','--module','NodeNext','--moduleResolution','NodeNext','--target','ES2022',join(output,'consumer-types.ts')],{cwd:output,stdio:'inherit',timeout:120000});
for(const name of ['client.js','client.d.ts','integration.mjs','integration.d.ts','worker.mjs'])assert.equal(await readFile(join(installed,'src',name),'utf8'),await readFile(join(root,'src',name),'utf8'));
for(const script of ['verify-offline-client.mjs','verify-offline-lifecycle.mjs','verify-offline-api.mjs','verify-offline.mjs','verify-offline-freshness.mjs','verify-offline-canonical.mjs'])execFileSync(process.execPath,[join(root,'scripts',script)],{cwd:root,stdio:'inherit',timeout:120000,env:{...process.env,OFFLINE_PACKAGE_ROOT:installed}});
console.log('Independent packed install, exact exports/notices and browser worker/client/API/freshness contracts passed:',output);
